# Generated by Django 4.0.4 on 2022-04-30 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bwfapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1', models.CharField(max_length=32)),
                ('team_2', models.CharField(max_length=32)),
                ('time', models.TimeField()),
                ('score_1', models.IntegerField(blank=True, null=True)),
                ('score_2', models.IntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bwfapi.group')),
            ],
        ),
    ]
